### ISSUE TITLE
关于自定义toast组件消失的问题。

### ISSUE THREAD

**Issue by BowinChow** [VincentWei/MiniGUI#101]
魏博士您好！
  我们之前讨论过组件组合的toast如何延时消失的问题，ref to: https://github.com/VincentWei/MiniGUI/issues/98. 今天我发现当关闭一个activity的一瞬间，之前已经消失的pieces会瞬间出现，随着activity一起关闭。其实关闭activity回调了onPaint,onClose方法，但是对于已经删除的组件应该不会重现。想请教这一问题可能的原因是什么呢？
祝好！

**Comment by VincentWei** [comment]
这个不清楚，您需要自己排查。
