### ISSUE TITLE
关于阿拉伯语小数点插入问题

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#106]
前几个问题单对于bidisledit的问题已经修复，现在有一个新的问题，就是在这个控件中随意输入英文+数字，同样采用微软雅黑字体，然后随机点击一个字符位置，然后再点击键盘插入一个小数点，这个小数点位置不会出现在插入符边上，而是会出现在离插入符一个英文字符之外的地方。
简单来说在插入符的位置插入小数点“.” ，这个插入的位置不对

**Comment by VincentWei** [comment]
3.0 有这个问题吗？另外，双向布局的时候，是不是小数点导致了字符的视觉位置发生变化？

**Comment by htk719809837** [comment]
3.0没有问题的，我们代码没有变更过。应该是5.0插入符引起的？

**Comment by VincentWei** [comment]
插入符调整不会引起这类情况。如果 3.0 没问题，应是底层多字符集支持的机制调整引起的。我们检查一下。

**Comment by htk719809837** [comment]
请问这个问题有查到吗

**Comment by htk719809837** [comment]
这个问题目前进度怎么样了，我们这边比较着急，希望可以在本周定位到

**Comment by VincentWei** [comment]
已修复，请从 `rel-5-0` 分支获取最新代码。

**Comment by htk719809837** [comment]
没有看到新的代码提交呢

**Comment by VincentWei** [comment]
pull 就是了。
