### ISSUE TITLE
关于阿拉伯小数点插入问题

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#108]
问题单详见 #106 

该问题经过验证并未被修复，并且引入了新问题：现在正常输入、删除小数点，小数点的位置也不对。

希望能够尽快修复

**Comment by VincentWei** [comment]
不对啊，您是不是从 master 分支上拿的代码？要用 `rel-5-0` 分支的代码。另外，引起这个问题的错误不在 bidisledit 控件本身，而在字体和字符集处理相关的代码中，要注意完整合并 font/ 和 newgdi/ 等其他位置的修改。

我们这边确认已修复了，也没有发现新问题。

**Comment by htk719809837** [comment]
已修复
