### ISSUE TITLE
关于函数接口咨询

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#113]
你好，有办法让GetTabbedTextExtentPoint支持BIDI文本吗？
我们这边相关功能需要用到这个接口，但是又不支持BIDI文本

**Comment by VincentWei** [comment]
我们看看。您只需要支持 ISO8859-6 字符集吧？

**Comment by htk719809837** [comment]
是的

**Comment by VincentWei** [comment]
好的。评估了一下，可以解决，本月内差不多可以完工。

**Comment by VincentWei** [comment]
相关接口及其实现已添加到 rel-5-0 分支。除了提到的接口之外，还增加了一些相关接口：

- ENHANCEMENTS:
  - Add new API GetACharsExtentPointEx().
   - Add new APIs GetTabbedACharsExtent(), GetTabbedACharsExtentPoint(), and GetTabbedACharsExtentPointEx().
   - Enhance two APIs GetTextExtentPoint() and GetTabbedTextExtentPoint() to support BIDI charsets.
- BUGFIXING:
   - Fix a typo: Achar2UChar() to AChar2UChar().

如有问题，请及时反馈。

注意要调用 `SetBIDIFlags(HDC_SCREEN, BIDI_FLAG_RTL);` 才会执行 BIDI 相关处理。
