### ISSUE TITLE
你好，咨询一下EDIT控件如何去除插入符呢？

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#114]
1、直接使用EDIT、SLEDIT、BIDIEDIT控件的话，有办法去除插入符嘛，DestroyCaret 貌似不太好使？
2、另外，看到可以通过getcapture和setcapture设置焦点，那是不是有取消焦点的方法，让焦点不在任何一个控件上呢？

**Comment by htk719809837** [comment]
或者说有没有全局禁用光标的方法，对所有窗口都生效呢？

**Comment by VincentWei** [comment]
插入符的控制，没有全局的方法。如果不希望输入框获得焦点显示插入符，可以设置输入框的风格为禁用状态：设置 `WS_DISABLED` 风格，或者调用 `EnableWindow(hwnd, FALSE)`。输入框为禁用状态时，不可获得焦点，也不会显示插入符，但仍然可以通过输入框的编辑接口来改变输入框的内容，比如要插入字符就向输入框发送 `EM_INSERTTEXT` 消息。

**Comment by VincentWei** [comment]
插入符的控制，没有全局的方法。如果不希望输入框获得焦点显示插入符，可以设置输入框的风格为禁用状态：设置 `WS_DISABLED` 风格，或者调用 `EnableWindow(hwnd, FALSE)`。输入框为禁用状态时，不可获得焦点，也不会显示插入符，但仍然可以通过输入框的编辑接口来改变输入框的内容，比如要插入字符就向输入框发送 `EM_INSERTTEXT` 消息。

**Comment by htk719809837** [comment]
好的，谢谢
