### ISSUE TITLE
关于MGI库的问题

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#115]
调用mgi在键入"吕"这类"lv"拼音后，查询到的其实是"l"的候选词；
如果要键入“吕”这个字，需要输入“lu”的拼音；
这个缺陷可以尽快帮忙修复吗，这边比较着急~

**Comment by VincentWei** [comment]
mGi 用的是 20 年前的开源输入法拼音码表，很老了，不好处理，我们也不维护了。试试绕转思路吧：

用户输入 lv 后，将其转换成 lu 再调用 mgi 的接口。

建议尽早切换到其他开源输入法，比如：<https://github.com/rime/librime>。用法可参考 mg-demos 仓库中的 SoftKbd2 示例程序：

<https://github.com/VincentWei/mg-demos>
