### ISSUE TITLE
bug report for mGNCS

### ISSUE THREAD

**Issue by 10km** [VincentWei/minigui#13]
the `mSpinbox` have a bug : the font selected is not effective on runt time.
for detail, please see my blog : https://blog.csdn.net/10km/article/details/81147355

I fixed it in my `mGNCS` source. 

because `mGNCS` have not opened git repository, I can't create pull request. so you can see also the commit : 
https://gitee.com/l0km/libmgncs-1.2.0/commit/0d9e1ea9e7c196c15853d05dd25d709d43669b1d

another litte issue,please see the commit: https://gitee.com/l0km/libmgncs-1.2.0/commit/720670dee25a9d44ecc8eaa802c787e638e9fee4

**Comment by 10km** [comment]
sorry,I see the `mGNCS`  repository. I will create pull request.

**Comment by VincentWei** [comment]
Ok, thanks!
