### ISSUE TITLE
作者请看看

### ISSUE THREAD

**Issue by byteman** [VincentWei/minigui#14]
我2008年前用过minigui开发过一个项目，当时公司还买了2.04的授权，现在一个项目我又想到来用minigui，发现minigui3.0，没想到现在minigui推荐的MGNCS加mstudio设计的这么反人类，简直难用至极，我做了10多年开发，还是第一次看到一个软件发展了20年，演化的如此难用。作者可以看看FlyThings OS，开发效率比mstudio+mgncs好用多了

**Comment by VincentWei** [comment]
Thanks for your comment.

You are partly right: miniStudio is not a mature software. But we did not recommend the developers to use miniStudio. We recommended the developers to use mGNCS. 

For our new MiniGUI projects, we only use miniStudio for prototype design. However, we are now heavily use mGNCS, and mGNCS4Touch as well for our new MiniGUI projects.

Of course, if you want, you can still use MiniGUI core to develop your projects.
