### ISSUE TITLE
enable-pngsupport bug

### ISSUE THREAD

**Issue by LiaoHuaping** [VincentWei/minigui#15]
My project exist libpng 1.6 version.  I try to config --enable-pngsupport to enable png suppport. But it's no work, is report "checking for png_check_sig in -lpng... no".  And i try to use old libpng of version 1.2.37, it's success. I think there are some problem to use libpng new version.

**Comment by VincentWei** [comment]
Generally, please run the following command if you are using Ubuntu Linux:

    $ sudo apt install libpng12-dev
