### ISSUE TITLE
suggest: support wayland

### ISSUE THREAD

**Issue by 1989wanghang** [VincentWei/minigui#16]
wayland is popular, in case of be compatible and easier hardware accel, support wayland in minigui will be grateful

**Comment by VincentWei** [comment]
Hi @1989wanghang ,

This is a good suggestion! In deed, we can write a NEWGAL engine based-on wayland for MiniGUI. I believe It will not be a very hard work. We will consider this.

However, I am not sure whether wayland is popular for embedded or IoT system. I know many IoT SoCs lack the support for basic 2D graphics acceleration interfaces. And there is not standard kernel interface. The system needs such a interface to handle the basic 2D graphics acceleration and integrate with OpenGL ES or OpenVG.

Thanks!
