### ISSUE TITLE
question: does minigui support safertos

### ISSUE THREAD

**Issue by xaeroyuan** [VincentWei/minigui#17]
Hi @VincentWei ,

I'm working on a project that plan to run gui on safertos under i.xm6ull board(cortex-A7 process).
I'm currently doing the evaluation of the gui libraries.
I want to know whether the minigui supports safertos.
If the answer is no, is there any change that can be done to support this?

**Comment by VincentWei** [comment]
Hi @xaeroyuan ,

MiniGUI had not run on Saftertos. However, I guess Safertos is a RTOS like VxWorks or uC/OS-II. So it is not a hard work to run MiniGUI on such OS. 

I suggest to try to run MiniGUI-Standalone on Saftertos first. MiniGUI-Standalone only depends on the standard ANSI C interface. If your OS does not support STDIO, you can just configure MiniGUI to use in-core resource, that is, all resource including bitmaps and fonts are compiled as binary data into MiniGUI library.

Good Luck!
