### ISSUE TITLE
出现了缺少cur文件的问题

### ISSUE THREAD

**Issue by meltsnow** [VincentWei/minigui#26]
4.0版本编译后尝试执行，提示KERNEL>InitGUI: Count not init mouse cursor!
上网查询在MiniGui.cfg文件中需要指定cur文件目录
然而我在系统根目录find / -name "*.cur"却没有找到这样的文件
请问这些文件是怎么生成的？谢谢

**Comment by VincentWei** [comment]
It seams that you did not install the resource files.

For a quick start, please use the scripts in the repo:

<https://github.com/VincentWei/build-minigui-4.0>

For the detailed description, please refer to:

<https://github.com/VincentWei/minigui-docs/blob/master/user-manual/MiniGUIUserManualQuickStart.md>
