### ISSUE TITLE
部分平台有可能导致黑屏，以下是分析报告

### ISSUE THREAD

**Issue by meltsnow** [VincentWei/minigui#28]
有部分平台在启动miniGUI的时候（32位色模式下）会出现画面全黑的情况，目前已知出现这种问题的平台会有如下特征：
控制台输入fbset，输出的结果中如下：
mode "800x1280-22"
        # D: 27.000 MHz, H: 28.785 kHz, V: 21.724 Hz
        geometry 800 1280 800 1280 32
        timings 37037 60 16 30 9 62 6
        accel false
        **rgba 0/0,0/0,0/0,0/0**
endmode
rgba这里变成了全0
而正常应该显示为：
rgba 8/16,8/8,8/0,8/24
看样子似乎是指定每个像素点中RGBA分量的长度和偏移量
目前我用fbset -rgba 8/16,8/8,8/0,8/24这样的命令行不通，只能通过修改代码来解决问题
目前是这样做的：
在miniGUI源码目录/src/newgal/fbcon/fbvideo.c中第621行插入如下代码
	vinfo.red.length=8;
	vinfo.green.length=8;
	vinfo.blue.length=8;
	vinfo.transp.length=8;
	vinfo.red.offset=16;
	vinfo.green.offset=8;
	vinfo.blue.offset=0;
	vinfo.transp.offset=24;
经过这样修改就正常了，但是毕竟是我个人的修改方式
这种问题有没有更好的解决方法？

**Comment by VincentWei** [comment]
This obviously is a bug of fb driver in the kernel. You should contact the chip vendor to resolve the problem: return the correct length information of the color components.
