### ISSUE TITLE
新版本取消了最小化窗口的功能吗？

### ISSUE THREAD

**Issue by meltsnow** [VincentWei/minigui#31]
有一份比较早期的minigui文档提到了窗口可以添加WS_MINIMIZE参数，让窗口可以最小化
然而3.0版本的文档则去掉了这部分，是否去掉了窗口可以最小化的功能？
因为我打算在proc模式下，做一个和演示中的mginit类似的桌面，可以将窗口最小化到任务栏（类似windows那种），但是似乎找不到可以最小化的方法
使用ShowWindow(hwnd,SW_HIDE)隐藏程序主窗口的话，窗口就不能再接收服务端发送的消息了
所以想请教下，是否在新版本中取消了窗口最小化的功能？

**Comment by VincentWei** [comment]
This style was reserved for future use. It was never implemented.

We have the plan to implement this style (as well the WS_MAXIMIZE style) in 5.x.
