### ISSUE TITLE
ShowWindow()运行原理问题

### ISSUE THREAD

**Issue by meltsnow** [VincentWei/minigui#38]
4.0版本中，在proc模式下，对某一进程的主窗口使用ShowWindow(SW_HIDE)后会出现无法接收由服务器程序发送的消息的情况，请问这是为什么？

**Comment by VincentWei** [comment]
Would you like to post some code to test this issue? Thanks in advance!

**Comment by meltsnow** [comment]
> Would you like to post some code to test this issue? Thanks in advance!

已经找到问题了，在接收消息后应该使用postmessage而不是sendmessage来隐藏窗口，否则会导致消息处理阻塞
