### ISSUE TITLE
If build not in source code dirctory, can't find ../mgconfig.h

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#4]
Source in directory 'minigui'
Build in directory 'build'

$ cd build
$ ../minigui/configure
$ make
  some code can't ../mgconfig.h

Then I add '-I$(abs_top_builddir)/src' to AM_CPPFLAGS for fixing it.

**Comment by VincentWei** [comment]
Not a real problem, and your solution is not good yet.
You should build MiniGUI in the root directory of the source code tree.
