### ISSUE TITLE
如果没使能SCROLLBAR编译lf_skin会出现错误

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#42]
lf_skin.c: In function 'get_scroll_status':
lf_skin.c:2671:26: error: 'CTRL_SCROLLBAR' undeclared (first use in this function)
     if (0 == strncasecmp(CTRL_SCROLLBAR, GetClassName(hWnd), strlen(CTRL_SCROLLBAR)))
                          ^~~~~~~~~~~~~~
lf_skin.c:2671:26: note: each undeclared identifier is reported only once for each function it appears in
lf_skin.c: In function 'draw_scrollbar':
lf_skin.c:2708:27: error: 'CTRL_SCROLLBAR' undeclared (first use in this function)
     if (0 == strncasecmp (CTRL_SCROLLBAR, GetClassName(hWnd), strlen(CTRL_SCROLLBAR))) {
                           ^~~~~~~~~~~~~~
lf_skin.c: In function 'draw_trackbar_thumb':
lf_skin.c:3005:19: error: 'TBS_VERTICAL' undeclared (first use in this function)
     if (dwStyle & TBS_VERTICAL) {
                   ^~~~~~~~~~~~
lf_skin.c:3042:19: error: 'LFRDR_TBS_PRESSED' undeclared (first use in this function)
     if (dwStyle & LFRDR_TBS_PRESSED)
                   ^~~~~~~~~~~~~~~~~
lf_skin.c:3044:24: error: 'LFRDR_TBS_HILITE' undeclared (first use in this function)
     else if (dwStyle & LFRDR_TBS_HILITE)
                        ^~~~~~~~~~~~~~~~
lf_skin.c: In function 'calc_trackbar_rect':
lf_skin.c:3072:19: error: 'TBS_BORDER' undeclared (first use in this function)
     if (dwStyle & TBS_BORDER) {
                   ^~~~~~~~~~
lf_skin.c:3086:19: error: 'TBS_VERTICAL' undeclared (first use in this function)
     if (dwStyle & TBS_VERTICAL) {
                   ^~~~~~~~~~~~
lf_skin.c: In function 'draw_trackbar':
lf_skin.c:3150:19: error: 'TBS_VERTICAL' undeclared (first use in this function)
     if (dwStyle & TBS_VERTICAL){

**Comment by VincentWei** [comment]
Scrollbar is a very basic control of MiniGUI. Please keep it enabled.
