### ISSUE TITLE
如果设置--disable-ctrlscrollview, 链接库时会报错

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#44]
listview.c:(.text+0x1f4): undefined reference to `scrolled_visible_to_content'
listview.c:(.text+0x208): undefined reference to `scrollview_is_in_item'
listview.c:(.text+0x228): undefined reference to `scrollview_get_item_adddata'

listview.c:(.text+0x2a8): undefined reference to `mglist_freeze'
listview.c:(.text+0x2c4): undefined reference to `mglist_freeze'
listview.c:(.text+0x2d8): undefined reference to `mglist_get_next_item'
listview.c:(.text+0x2e0): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x2fc): undefined reference to `scrollview_set_item_height'
listview.c:(.text+0x33c): undefined reference to `mglist_get_next_item'

listview.c:(.text+0x35c): undefined reference to `mglist_getitem_byindex'
listview.c:(.text+0x364): undefined reference to `scrollview_get_item_adddata'

listview.c:(.text+0x390): undefined reference to `scrolled_visible_to_content'

listview.c:(.text+0xfe4): undefined reference to `ScrollViewCtrlProc'
listview.c:(.text+0x1278): undefined reference to `mglist_get_next_item'
listview.c:(.text+0x127c): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x13d8): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x141c): undefined reference to `mglist_hilight_item'
listview.c:(.text+0x1624): undefined reference to `scrollview_get_item_rect'
listview.c:(.text+0x1650): undefined reference to `scrollview_init'
listview.c:(.text+0x1684): undefined reference to `scrolled_set_margins'
listview.c:(.text+0x1748): undefined reference to `scrollview_destroy'
listview.c:(.text+0x1810): undefined reference to `scrollview_draw'
listview.c:(.text+0x1840): undefined reference to `mglist_refresh_item'
listview.c:(.text+0x1ba0): undefined reference to `ScrollViewCtrlProc'
listview.c:(.text+0x1e70): undefined reference to `mglist_get_next_item'
listview.c:(.text+0x1e74): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x2044): undefined reference to `scrollview_add_item_ex'
listview.c:(.text+0x20b0): undefined reference to `scrollview_add_item'
listview.c:(.text+0x2234): undefined reference to `mglist_refresh_item'
listview.c:(.text+0x2384): undefined reference to `mglist_get_next_item'
listview.c:(.text+0x2388): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x240c): undefined reference to `scrollview_del_item'
listview.c:(.text+0x24b0): undefined reference to `mglist_get_next_item'
listview.c:(.text+0x24b4): undefined reference to `scrollview_get_item_adddata'
listview.c:(.text+0x2554): undefined reference to `mglist_make_item_visible'
listview.c:(.text+0x2584): undefined reference to `mglist_hilight_item'
listview.c:(.text+0x2684): undefined reference to `scrollview_set_item_height'
listview.c:(.text+0x26b8): undefined reference to `scrolled_set_margins'

**Comment by VincentWei** [comment]
Scrollview is a very basic control of MiniGUI. Please keep it enabled.
If you disable scrollview and other basic controls (such as scrollbar), you need to disable other controls or features which use these control. Sorry that the configure.ac script does not check all of these dependencies.
