### ISSUE TITLE
RegisterListenFD 有个逻辑有些不合理

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#46]
if (ok && msg_queue->maxfd < fd) {
         msg_queue->maxfd = fd;
        return TRUE;
}

应该改为下面更合理
if (ok) {
       if (msg_queue->maxfd < fd)
            msg_queue->maxfd = fd;
        return TRUE;
}

**Comment by VincentWei** [comment]
Thanks for your report. I have changed the code to:

```
        if (ok) { 
            if (msg_queue->maxfd < fd) {
                msg_queue->maxfd = fd;
            }

            return TRUE;
        }
```
