### ISSUE TITLE
minigui not fount hb-ft.h and --with_ft2_includes is invalid

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/minigui#52]
Hello, Mr Wei :
     miniGUI 5.0.3
     I have two issues.  
     1. hb-ft.h miss after make install harfbuzz, it's not be fount in include/harfbuzz.
     out info :  ....... shape-glyphs-complex.c:76:19: fatal error: hb-ft.h: No such file or directory
 #include <hb-ft.h>
     2.--with_ft2_includes is not effect. I guess is a bug  :
     file <configure.ac:2240> 2240     with_ft2_includes=""
                                                                                                                                                                Thanks

**Comment by VincentWei** [comment]
1) Which version of harfbuzz are you using?

2) I will check this.

Thanks for your report.

**Comment by steprun** [comment]
```
configure.ac
@@ -2236,7 +2253,7 @@ if test "x$build_ttf_support" = "xyes"; then
--
AC_DEFINE(_MGFONT_FT2, 1,
        [Define if support TrueType/OpenType fonts based on FreeType2])
 - with_ft2_includes=""
+ #with_ft2_includes=""
```

**Comment by huohongpeng** [comment]
> 1. Which version of harfbuzz are you using?
> 2. I will check this.
> 
> Thanks for your report.
Mr Wei：
Thanks for your reply， Version is <harfbuzz-2.5.3>.
Thanks

**Comment by VincentWei** [comment]
Thanks for your fix. I have merge it to `rel-5-0` branch.

For the `hb-ft.h` header file, I checked the source code of HarfBuzz 2.5.3, and found that there was the file in the source tree. I think that you did not installed hb correctly. Please check it.

**Comment by huohongpeng** [comment]
Thanks Wei
