### ISSUE TITLE
libharfbuzzex.so.0.20501.0 如何得到

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/minigui#53]
ln -s $TINA_DIR/lichee/linux-4.4/include/uapi/linux/input-event-codes.h input-event-codes.h
cd $WORK_DIR/rootfs/usr/local/lib
sudo ln -s libharfbuzzex.so.0.20501.0 libharfbuzz.so
cd $WORK_DIR/minigui

编译harfbuzz后只会生成libharfbuzz-subset.so.0.20501.0和libharfbuzz.so.0.20501.0，并没有harfbuzzex.编译过程中也打开了--with-exunicode=yes

**Comment by huohongpeng** [comment]
我看到了harfbuzz的提交记录，把ex后缀删除了，使用外部unicode这种方式修改了，所以应该不用harfbuzzex了吧

**Comment by VincentWei** [comment]
Yes, we now use the standard HarfBuzz release.
