### ISSUE TITLE
minigui --enable-videoshadow导致其他组件编译失败

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/minigui#54]
### **minigui5.0.3**
无意中使能了--enable-videoshadow，发现了一些报错，查找资料说shadow可以实现旋转屏幕。忽然对shadow起了兴趣。
1.qt或者android都支持屏幕旋转，minigui是不是支持屏幕旋转？
2.看过有地方说shadow可以支持旋转，但是--enable-videoshadow其他组件都会报找不到GAL_GetVideo参考。grep 整个minigui确实只定义了一个静态的GAL_GetVideo。
3.在minigui/src/newgal/video.c:176：static GAL_VideoDevice *GAL_GetVideo(const char* driver_name)。
  而在minigui/src/newgal/shadow/shadow.c:113: extern GAL_VideoDevice *GAL_GetVideo(const char* driver_name, BOOL check_compos);
minigui/src/newgal/shadow/shadow.c:308:    real_device = GAL_GetVideo (engine, FALSE);
参数参数不一致。不知道这两个函数是否相同？还是说shadow中的 GAL_GetVideo 需要自己实现？

**Comment by VincentWei** [comment]
This code has not been maintained for a long time. Welcome any pull request to fix the problem.
