### ISSUE TITLE
建议将udev更换为eudev

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/minigui#55]
目前看到minigui可以支持libinput，而libinput需要libudev这个依赖。目前看到作者嵌入式自动化编译脚本中使用的是udev，编译udev需要很多依赖，移植起来比较麻烦。udev项目比较老了，现在eudev兼容udev，希望作者能替换掉udev。我在学习过程中，已将尝试编译eudev，过程相对udev简单很多，并且能正确支持libinput。

eudev项目：https://github.com/gentoo/eudev/tree/master

**Comment by VincentWei** [comment]
Thanks for your advice. We will consider this.
