### ISSUE TITLE
建议作者在minigui工程中加入input-event-codes.h

### ISSUE THREAD

**Issue by huohongpeng** [VincentWei/minigui#56]
看到minigui中使用linux中的input-event-codes.h头文件，桌面的系统中会有这个头文件，但是当交叉编译时不会搜做桌面系统头文件路径，导致minigui编译出错。我看到libinput工程源码中就自己包含了这个文件，minigui是一个出色的可移植库，希望作者将input-event-codes.h包含在minigui工程中，提高可移植性。

ial/random.c:129:#include <linux/input-event-codes.h>
ial/linux-libinput.c:182:#include <linux/input-event-codes.h>

**Comment by VincentWei** [comment]
Oh, no. This is a bad idea. As a middleware, we can not include such a system header in our source code tree.

**Comment by kmalloc8** [comment]
> 看到minigui中使用linux中的input-event-codes.h头文件，桌面的系统中会有这个头文件，但是当交叉编译时不会搜做桌面系统头文件路径，导致minigui编译出错。我看到libinput工程源码中就自己包含了这个文件，minigui是一个出色的可移植库，希望作者将input-event-codes.h包含在minigui工程中，提高可移植性。
> 
> ial/random.c:129:#include <linux/input-event-codes.h>
> ial/linux-libinput.c:182:#include <linux/input-event-codes.h>

最后这个怎么合进去？

**Comment by VincentWei** [comment]
We have ignored this.
