### ISSUE TITLE
请问多语言是有什么方式在minigui中实现?

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#59]
请问多语言是有什么方式在minigui中实现?

**Comment by VincentWei** [comment]
You can refer to <https://github.com/VincentWei/mg-demos/tree/master/cbplusui>

It uses GNU gettext .mo files to implement support for multi-language.

**Comment by steprun** [comment]
> You can refer to https://github.com/VincentWei/mg-demos/tree/master/cbplusui
> 
> It uses GNU gettext .mo files to implement support for multi-language.

这个示例应该是刚启动的时候可以用, 如果多个窗口同时显示, 在设置项中修改应该是不能同时把其它窗口为多语言文字修改吧?

**Comment by VincentWei** [comment]
Sorry that I can not understand your question. You can use your own solution to support L10N.
