### ISSUE TITLE
GetNextMainWindow 没法获得 第一个MainWindow

### ISSUE THREAD

**Issue by steprun** [VincentWei/minigui#61]
hMainWnd == HWND_NULL || MG_IS_NORMAL_MAIN_WINDOW (hMainWnd) 这两个条件就没有方法获得第一个窗口, dskGetNextMainWindow 却可以通过传空值来获得第一个窗口

**Comment by VincentWei** [comment]
Obviously, this is a bug. Thanks for your report!

**Comment by VincentWei** [comment]
The condition should be changed to:

hMainWnd != HWND_NULL && !MG_IS_NORMAL_MAIN_WINDOW (hMainWnd)

**Comment by Aaron-mo** [comment]
> Obviously, this is a bug. Thanks for your report!

Sorry, this issue does not seem to be fixed
