### ISSUE TITLE
minigui是否支持JAVA JNI？

### ISSUE THREAD

**Issue by meltsnow** [VincentWei/minigui#63]
我尝试了下打算用JAVA的JNI来支持MINIGUI，结果发现会崩溃，请问minigui是否能支持JAVA？

**Comment by VincentWei** [comment]
In 2007, FMSoft developed a product called mgPeer, which let Java application runs on MiniGUI.
So, it is possible to run Java app on MiniGUI.

**Comment by meltsnow** [comment]
我的意思是，用JAVA来写MINIGUI的程序（proc模式），可行么？

**Comment by VincentWei** [comment]
理论上当然是可行的。
