### ISSUE TITLE
新版本支持64位吗？有计划往龙芯上移植吗？

### ISSUE THREAD

**Issue by maikebing** [VincentWei/minigui#64]
我在使用老版本 2.0.4 ， 一些 地方存在句柄和 无符号4字节整型转换的代码。 
新版本有考虑64位编译器吗？
近期我在尝试往龙芯移植， 不知道是否有现成的资料？

**Comment by maikebing** [comment]
https://github.com/VincentWei/minigui/blob/4e0cd7455235b04091cc39b727b8a25153bf3530/include/common.h#L402

**Comment by VincentWei** [comment]
MiniGUI provided support for 64-bit platform since version 3.2.0. See

<https://github.com/VincentWei/minigui/blob/rel-3-2/RELEASE-NOTES.md>

Also note that the latest stable version of MiniGUI is 5.0.5. We suggest that your upgrade to use the latest MiniGUI version.
