### ISSUE TITLE
2.0.4 版本中的 SetWindowElementColorEx  在新的5.0.5 中用什么替代？

### ISSUE THREAD

**Issue by maikebing** [VincentWei/minigui#65]

**Comment by VincentWei** [comment]
Use `SetWindowElementAttr` instead.

**Comment by maikebing** [comment]
感谢。

**Comment by VincentWei** [comment]
Note that your company should renew the commercial license if you want to upgrade to MiniGUI 5.0. Please contact <sales@minigui.com>.
