### ISSUE TITLE
5.0.8/newgdi/gdi.c中函数InitSubDC的问题

### ISSUE THREAD

**Issue by DaVinci79** [VincentWei/minigui#81]
看了5.0.8代码，newgdi/gdi.c中dc_InitClipRgnInfo函数是空，去掉对DCSlot的lcrgn和ecrgn的初始化，这可能会导致InitSubDC调用CopyRegion时，由于lcrgn和ecrgn的heap为NULL，引起段错。
mgncs4touch\samples下例程settingtableview.c、tableview.c和hscrollview.c这三个例子就会出现段错，因为采用ncsCreateMainWindow创建主窗口的。
测试环境ubuntu20.04 LTS

**Comment by VincentWei** [comment]
Thanks for your bug report!

**Comment by VincentWei** [comment]
I have fixed the bug: call `InitClipRgn` before calling `CopyRegion`:

```c
    InitClipRgn (&pdc->lcrgn, &__mg_FreeClipRectList);
    MAKE_REGION_INFINITE(&pdc->lcrgn);
    InitClipRgn (&pdc->ecrgn, &__mg_FreeClipRectList);
```
