### ISSUE TITLE
newgal  有没有支持 vnc  

### ISSUE THREAD

**Issue by maikebing** [VincentWei/minigui#82]
比如 支持 UI和IO部分 跟vnc进行配合

**Comment by maikebing** [comment]
或者说有没有意向？

**Comment by VincentWei** [comment]
Currently, there is no such support for VNC as NEWGAL/IAL engines in MiniGUI.
You can contact FMSoft (sales@fmsoft.cn) if you have some budgets to implement them.

**Comment by maikebing** [comment]
已经联系

**Comment by maikebing** [comment]
收件人邮件地址（sales@fmsoft.cn）不存在，邮件无法送达。

**Comment by VincentWei** [comment]
Sorry for the wrong email address. 

Please send a message to <sales@minigui.com> or visit one of the following webpages:

- <https://minigui.fmsoft.cn/contact>
- <https://www.fmsoft.cn/about/contact>
