### ISSUE TITLE
minigui是不是未考虑过动态切换分辨率的情况？

### ISSUE THREAD

**Issue by chenyinen** [VincentWei/minigui#86]
minigui默认启动分辨率是配置写死的，线程模式下如果需要不杀进程切分辨率我应该怎么做？配置文件剥离出分辨率情况下先调用TerminateGUI结束任务然后再重新调用一次InitGUI合适嘛！

**Comment by VincentWei** [comment]
So far, MiniGUI doesn't consider the change of the resolution on the fly. You can try the way you said.
