### ISSUE TITLE
关于编译以后移动minigui位置重新编译报错问题

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#88]
是这样的，目前打算将3.0的版本替换为5.0，但是minigui5.0下载下来以后我放到项目A路径下，配置好minigui以后，重新拷贝到项目B路径下进行./configure   make -j的命令就出现如下报错

或者说在项目A路径下编译以后，拷贝配置好的minigui到项目B路径下，重新执行./configure   make -j，也会出现如下的错误；

可以肯定的是直接放到项目A或者B下面，配置好minigui以后，在进行编译是没有问题的，一旦minigui位置发生移动（无论是否进行过编译，只要修改过一些源代码，没有新增文件），编译就会报错，试过重新利用automake和autoconf，都不行

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh 
******/libminigui-5.0.9/missing aclocal-1.16 
********/libminigui-5.0.9/missing: 行 81: aclocal-1.16: 未找到命令
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>

**Comment by VincentWei** [comment]
autotool 生成的 makefile 文件中，使用的一般都是绝对路径。直接移动一个项目到其他位置，就会导致重新配置，这时就会出现重新运行生成 configure 脚本时的原始工具，也就是截图中提到的 aclocal-1.16 等。

请参考 https://github.com/VincentWei/build-minigui-5.0 中的脚本来构建 MiniGUI。
