### ISSUE TITLE
关于一个崩溃问题

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/MiniGUI#94]
使用场景：
A界面点击按钮进入B界面，B界面有一个两秒的定时器关闭自己，并且也有一个按钮（此处的要求是，按钮响应抬起事件，按下不响应）点击以后可以关闭自己，回到A界面。
在进入B界面后，一直按在关闭按钮上，等待定时器关闭B界面，返回到A界面后，抬起，程序卡死或者崩溃，目前只有在切换界面的时候重新发送SETCPATURE才可以解决这个问题，但是这个问题应该是底层消息处理的问题。

当前界面不存在了，那么就理应不去响应当前界面的消息（即使按钮这里的要求是抬起响应）....

**Comment by VincentWei** [comment]
多谢反馈，我们排查一下。

**Comment by VincentWei** [comment]
已修复相关缺陷，请从 `rel-5-0` 分支更新代码。

**Comment by htk719809837** [comment]
测试已修复
